name: knee_dl_app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.3
  - tensorflow=2.10.0
  - matplotlib=3.6.0 # Pinned for compatibility
  - pandas=1.5.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.2
  - seaborn=0.11.2
  - streamlit
  - lime
  - shap
  - pip:
    - Pillow==9.2.0 # Pin Pillow version for compatibility with other libraries
